"use client";
import Image from "next/image";
import Link from "next/link";
import { Minus, Plus, ShoppingBag, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { formatPrice } from "@/lib/utils";
import { useCartStore } from "@/stores/cart-store";

export default function CartPage() { const items = useCartStore((state) => state.items); const remove = useCartStore((state) => state.remove); const setQuantity = useCartStore((state) => state.setQuantity); const total = items.reduce((sum, item) => sum + Number(item.product.sale_price) * item.quantity, 0); return <div className="container py-10"><p className="font-bold text-brand-600">GIỎ HÀNG</p><h1 className="mt-2 text-3xl font-black">Sản phẩm bạn đã chọn</h1>{!items.length ? <div className="state-box mt-8"><ShoppingBag/>Giỏ hàng đang trống.<Button asChild><Link href="/products">Khám phá sản phẩm</Link></Button></div> : <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_340px]"><div className="space-y-3">{items.map(({ product, quantity }) => <article key={product.id} className="flex gap-4 rounded-2xl border bg-white p-4"><div className="relative h-24 w-28 shrink-0 overflow-hidden rounded-xl bg-slate-50"><Image src={product.image_url} alt={product.name} fill unoptimized className="object-cover"/></div><div className="min-w-0 flex-1"><Link href={`/products/${product.slug}`} className="font-bold hover:text-brand-600">{product.name}</Link><p className="mt-1 font-black text-red-600">{formatPrice(product.sale_price)}</p><div className="mt-3 flex items-center gap-2"><button aria-label="Giảm số lượng" className="rounded border p-1" onClick={() => setQuantity(product.id, quantity - 1)}><Minus className="h-4 w-4"/></button><span className="w-7 text-center">{quantity}</span><button aria-label="Tăng số lượng" className="rounded border p-1" onClick={() => setQuantity(product.id, quantity + 1)}><Plus className="h-4 w-4"/></button></div></div><button aria-label="Xóa" onClick={() => remove(product.id)} className="text-slate-400 hover:text-red-600"><Trash2/></button></article>)}</div><aside className="h-fit rounded-2xl border bg-white p-6 shadow-card"><h2 className="text-xl font-bold">Tóm tắt đơn hàng</h2><div className="mt-5 flex justify-between text-sm"><span>Tạm tính</span><strong>{formatPrice(total)}</strong></div><div className="mt-3 flex justify-between text-sm"><span>Phí vận chuyển</span><strong>Miễn phí</strong></div><div className="mt-5 flex justify-between border-t pt-5 text-lg"><strong>Tổng cộng</strong><strong className="text-red-600">{formatPrice(total)}</strong></div><Button className="mt-6 w-full" size="lg" onClick={() => toast.success("Checkout demo đã được ghi nhận")}>Checkout (demo)</Button><p className="mt-3 text-center text-xs text-slate-400">Chưa phát sinh thanh toán thật.</p></aside></div>}</div>; }
